defmodule CoreTest do
  use ExUnit.Case, async: true

  # # --- test generated by documentation of public APIs
  # doctest Hal.IrcHandler
  # doctest Hal.Tool
  # doctest Hal.Keeper
  # doctest Hal.Shepherd
  # doctest Hal.PluginReminder
  # doctest Hal.PluginBrain
  # doctest Hal.PluginTime
  # doctest Hal.PluginWeather

  # --- real unit tests

end
