FROM docker.io/elixir:1.7.4-alpine

RUN apk --upgrade --no-cache add make bash

# run as hal
RUN adduser -D hal
USER hal

# set a default working directory
ENV APP /app
WORKDIR $APP

# execute the default make goal
CMD make
